services:
  node:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/data || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    networks:
      - app-network   # 新增这一行

  web:
    build: ./web
    ports:
      - "80:80"
    depends_on:
      - node
        # condition: service_healthy
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge